services:
  catalog.api:
    image: catalogapi:dev
    build:
      args:
        LAUNCHING_FROM_VS: true
        BUILD_CONFIGURATION: Debug
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Catalog.API"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_catalog.api$
    volumes:
      - C:\Users\edrin\OneDrive\Desktop\Work Space\Ecommerce\Services\Catalog\Catalog.API:/app:rw
      - C:\Users\edrin\OneDrive\Desktop\Work Space\Ecommerce:/src:rw
      - C:\Users\edrin\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_catalog.api$
      - C:\Users\edrin\AppData\Roaming\ASP.NET\Https:/root/.aspnet/https:ro
      - C:\Users\edrin\AppData\Roaming\ASP.NET\Https:/home/app/.aspnet/https:ro
      - C:\Users\edrin\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro
      - C:\Users\edrin\AppData\Roaming\Microsoft\UserSecrets:/home/app/.microsoft/usersecrets:ro
      - C:\Program Files\Microsoft Visual Studio\18\Insiders\MSBuild\Sdks\Microsoft.Docker.Sdk\tools\linux-x64\net8.0:/VSTools:ro
      - C:\Program Files\Microsoft Visual Studio\18\Insiders\Common7\IDE\extensions\Microsoft\managedprojectsystem\HotReload:/HotReloadAgent:ro

    entrypoint: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --wait"
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_catalog.api$ \"/app/bin/Debug/net8.0/Catalog.API.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --stop dotnet"
    tty: true